# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('is_resolved', models.IntegerField()),
                ('description', models.CharField(max_length=350)),
                ('timestamp', models.DateTimeField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'incident_log',
                'managed': False,
            },
        ),
    ]
